org: jhon1234
app: pdf-generate-html
service: pdf-generate-html
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2

functions:
  function1:
    handler: index.handler
    events:
      - httpApi:
          path: /genrerate-pdf-using-html
          method: GET

plugins:
  - serverless-offline
